name: MiniGameWorld-Controller
main: com.minigameworld.controller.MiniGameWorldControllerMain
version: 0.6
author: worldbiomusic
api-version: 1.14
depend: [MiniGameWorld]

commands:
  mwcontrol:
    aliases: [mwc]
    